export const AUTH_STARTED = "AUTH_STARTED";
export const AUTH_SUCCESSFUL = "AUTH_SUCCESSFUL";
export const AUTH_FAILED = "AUTH_FAILED";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const DOWNLOAD_CSV_FILE_STARTED = "DOWNLOAD_CSV_FILE_STARTED";
export const DOWNLOAD_CSV_FILE_SUCCESSFUL = "DOWNLOAD_CSV_FILE_SUCCESSFUL";
export const DOWNLOAD_CSV_FILE_FAILED = "DOWNLOAD_CSV_FILE_FAILED";

export const INITIALIZE_LOAN_ENTRIES_STARTED =
  "INITIALIZE_LOAN_ENTRIES_STARTED";
export const INITIALIZE_LOAN_ENTRIES_SUCCESSFUL =
  "INITIALIZE_LOAN_ENTRIES_SUCCESSFUL";
export const INITIALIZE_LOAN_ENTRIES_FAILED = "INITIALIZE_LOAN_ENTRIES_FAILED";

export const SET_AUTH_REDIRECT_PATH = "SET_AUTH_REDIRECT_PATH";

export const SET_URL_PARAMS = "SET_URL_PARAMS";
